CREATE TABLE password_reset_token (
                                      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                      token VARCHAR(255) NOT NULL,
                                      email VARCHAR(255) NOT NULL,
                                      expiry_date TIMESTAMP NOT NULL
);

-- Индекс для быстрого поиска по email
CREATE INDEX idx_password_reset_token_email ON password_reset_token(email);

-- Индекс для быстрого поиска по токену
CREATE INDEX idx_password_reset_token_token ON password_reset_token(token);